# NOTE(artcz): There's probably a better way of managing the variables
# I put everything as host variables because it was easy to modify single file
# when working on the poc
all:
  hosts:
    static_website_test_1_setup:
      ansible_host: static-preview-v2.artcz.pl
      ansible_user: root
      nginx_user: nginx_user
      static_content_user: static_content_user

    static_website_test_1_nginx:
      ansible_host: static-preview-v2.artcz.pl
      ansible_user: nginx_user
      static_content_user: static_content_user
      domain_name: static-preview-v2.artcz.pl
      letsencrypt_email: "artur+test@europython.eu"
      letsencrypt_rsa_key_size: 4096

    static_website_test_1_static_content:
      ansible_host: static-preview-v2.artcz.pl
      ansible_user: static_content_user
